//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trangsuc.ServiceReferenceSanpham {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sanpham_DTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceTrangsuc")]
    [System.SerializableAttribute()]
    public partial class Sanpham_DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChatlieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiasanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trangsuc.ServiceReferenceSanpham.Loaisanpham_DTO LoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SanphammoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenloaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TensanphamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chatlieu {
            get {
                return this.ChatlieuField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatlieuField, value) != true)) {
                    this.ChatlieuField = value;
                    this.RaisePropertyChanged("Chatlieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Giasanpham {
            get {
                return this.GiasanphamField;
            }
            set {
                if ((this.GiasanphamField.Equals(value) != true)) {
                    this.GiasanphamField = value;
                    this.RaisePropertyChanged("Giasanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hinhanh {
            get {
                return this.HinhanhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhanhField, value) != true)) {
                    this.HinhanhField = value;
                    this.RaisePropertyChanged("Hinhanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trangsuc.ServiceReferenceSanpham.Loaisanpham_DTO Loai {
            get {
                return this.LoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiField, value) != true)) {
                    this.LoaiField = value;
                    this.RaisePropertyChanged("Loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Masanpham {
            get {
                return this.MasanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.MasanphamField, value) != true)) {
                    this.MasanphamField = value;
                    this.RaisePropertyChanged("Masanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sanphammoi {
            get {
                return this.SanphammoiField;
            }
            set {
                if ((this.SanphammoiField.Equals(value) != true)) {
                    this.SanphammoiField = value;
                    this.RaisePropertyChanged("Sanphammoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tenloai {
            get {
                return this.TenloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenloaiField, value) != true)) {
                    this.TenloaiField = value;
                    this.RaisePropertyChanged("Tenloai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tensanpham {
            get {
                return this.TensanphamField;
            }
            set {
                if ((object.ReferenceEquals(this.TensanphamField, value) != true)) {
                    this.TensanphamField = value;
                    this.RaisePropertyChanged("Tensanpham");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loaisanpham_DTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceTrangsuc")]
    [System.SerializableAttribute()]
    public partial class Loaisanpham_DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaloaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenloaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maloai {
            get {
                return this.MaloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaloaiField, value) != true)) {
                    this.MaloaiField = value;
                    this.RaisePropertyChanged("Maloai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tenloai {
            get {
                return this.TenloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenloaiField, value) != true)) {
                    this.TenloaiField = value;
                    this.RaisePropertyChanged("Tenloai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSanpham.IServiceSanpham")]
    public interface IServiceSanpham {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/GetAllSp", ReplyAction="http://tempuri.org/IServiceSanpham/GetAllSpResponse")]
        Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetAllSp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/GetAllLoaiSp", ReplyAction="http://tempuri.org/IServiceSanpham/GetAllLoaiSpResponse")]
        Trangsuc.ServiceReferenceSanpham.Loaisanpham_DTO[] GetAllLoaiSp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/GetLoaisp", ReplyAction="http://tempuri.org/IServiceSanpham/GetLoaispResponse")]
        Trangsuc.ServiceReferenceSanpham.Loaisanpham_DTO GetLoaisp(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/GetSpBc", ReplyAction="http://tempuri.org/IServiceSanpham/GetSpBcResponse")]
        Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetSpBc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/GetSpMoi", ReplyAction="http://tempuri.org/IServiceSanpham/GetSpMoiResponse")]
        Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetSpMoi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/GetSpCungLoai", ReplyAction="http://tempuri.org/IServiceSanpham/GetSpCungLoaiResponse")]
        Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetSpCungLoai(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/Find", ReplyAction="http://tempuri.org/IServiceSanpham/FindResponse")]
        Trangsuc.ServiceReferenceSanpham.Sanpham_DTO Find(string masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/Insert", ReplyAction="http://tempuri.org/IServiceSanpham/InsertResponse")]
        bool Insert(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/Update", ReplyAction="http://tempuri.org/IServiceSanpham/UpdateResponse")]
        bool Update(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/Delete", ReplyAction="http://tempuri.org/IServiceSanpham/DeleteResponse")]
        bool Delete(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanpham/Kichhoat", ReplyAction="http://tempuri.org/IServiceSanpham/KichhoatResponse")]
        bool Kichhoat(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSanphamChannel : Trangsuc.ServiceReferenceSanpham.IServiceSanpham, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSanphamClient : System.ServiceModel.ClientBase<Trangsuc.ServiceReferenceSanpham.IServiceSanpham>, Trangsuc.ServiceReferenceSanpham.IServiceSanpham {
        
        public ServiceSanphamClient() {
        }
        
        public ServiceSanphamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSanphamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSanphamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSanphamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetAllSp() {
            return base.Channel.GetAllSp();
        }
        
        public Trangsuc.ServiceReferenceSanpham.Loaisanpham_DTO[] GetAllLoaiSp() {
            return base.Channel.GetAllLoaiSp();
        }
        
        public Trangsuc.ServiceReferenceSanpham.Loaisanpham_DTO GetLoaisp(string maloai) {
            return base.Channel.GetLoaisp(maloai);
        }
        
        public Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetSpBc() {
            return base.Channel.GetSpBc();
        }
        
        public Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetSpMoi() {
            return base.Channel.GetSpMoi();
        }
        
        public Trangsuc.ServiceReferenceSanpham.Sanpham_DTO[] GetSpCungLoai(string maloai) {
            return base.Channel.GetSpCungLoai(maloai);
        }
        
        public Trangsuc.ServiceReferenceSanpham.Sanpham_DTO Find(string masp) {
            return base.Channel.Find(masp);
        }
        
        public bool Insert(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham) {
            return base.Channel.Insert(sanpham);
        }
        
        public bool Update(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham) {
            return base.Channel.Update(sanpham);
        }
        
        public bool Delete(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham) {
            return base.Channel.Delete(sanpham);
        }
        
        public bool Kichhoat(Trangsuc.ServiceReferenceSanpham.Sanpham_DTO sanpham) {
            return base.Channel.Kichhoat(sanpham);
        }
    }
}
