//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadon
    {
        public int mahoadon { get; set; }
        public string masanpham { get; set; }
        public int soluong { get; set; }
        public int giasanpham { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
