//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public hoadon()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
        }
    
        public int mahoadon { get; set; }
        public string tendangnhap { get; set; }
        public DateTime ngaymuahang { get; set; }
        public string diadiemgiaohang { get; set; }
        public string trangthai { get; set; }
        public string sdt { get; set; }
        public DateTime ngaygiaohang { get; set; }
    
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        public virtual nguoidung nguoidung { get; set; }
    }
}
