//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaisanpham
    {
        public loaisanpham()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        public string maloai { get; set; }
        public string tenloai { get; set; }
    
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
