//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        public nguoidung()
        {
            this.hoadons = new HashSet<hoadon>();
        }
    
        public string username { get; set; }
        public string hoten { get; set; }
        public string password { get; set; }
        public DateTime ngaysinh { get; set; }
        public int gioitinh { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public int maphanquyen { get; set; }
        public bool useran { get; set; }
    
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual phanquyen phanquyen { get; set; }
    }
}
