//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class phanquyen
    {
        public phanquyen()
        {
            this.nguoidungs = new HashSet<nguoidung>();
        }
    
        public int maphanquyen { get; set; }
        public string quyen { get; set; }
    
        public virtual ICollection<nguoidung> nguoidungs { get; set; }
    }
}
