//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieunhap
    {
        public phieunhap()
        {
            this.chitietphieunhaps = new HashSet<chitietphieunhap>();
        }
    
        public string maphieunhap { get; set; }
        public string tennguoilap { get; set; }
        public DateTime ngaylap { get; set; }
        public string trangthai { get; set; }
    
        public virtual ICollection<chitietphieunhap> chitietphieunhaps { get; set; }
    }
}
