//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuxuat
    {
        public phieuxuat()
        {
            this.chitietphieuxuats = new HashSet<chitietphieuxuat>();
        }
    
        public string maphieuxuat { get; set; }
        public string tennguoilap { get; set; }
        public DateTime ngaylap { get; set; }
        public string trangthai { get; set; }
    
        public virtual ICollection<chitietphieuxuat> chitietphieuxuats { get; set; }
    }
}
