//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTrangsuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public sanpham()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
            this.chitietphieunhaps = new HashSet<chitietphieunhap>();
            this.tonkhoes = new HashSet<tonkho>();
            this.chitietphieuxuats = new HashSet<chitietphieuxuat>();
        }
    
        public string masanpham { get; set; }
        public string tensanpham { get; set; }
        public string chatlieu { get; set; }
        public int giasanpham { get; set; }
        public int sanphammoi { get; set; }
        public string hinhanh { get; set; }
        public string maloai { get; set; }
    
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        public virtual ICollection<chitietphieunhap> chitietphieunhaps { get; set; }
        public virtual loaisanpham loaisanpham { get; set; }
        public virtual ICollection<tonkho> tonkhoes { get; set; }
        public virtual ICollection<chitietphieuxuat> chitietphieuxuats { get; set; }
    }
}
